name: release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: |
          The version to release. Must be a valid semver string.
        required: true

jobs:
  verify-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: mukunku/tag-exists-action@v1.2.0
        id: check-tag
        name: check if tag already exists
        with:
          tag: ${{ github.event.inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: fail if tag already exists
        if: ${{ steps.check-tag.outputs.exists == 'true' }}
        run: exit 1

  publish-release:
    runs-on: ubuntu-latest
    needs: [verify-tag]
    steps:
    - name: Parse semver string
      id: semver_parser
      uses: booxmedialtd/ws-action-parse-semver@v1.4.7
      with:
        input_string: ${{ github.event.inputs.tag }}
        version_extractor_regex: 'v(.*)$'
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.inputs.tag }}
        commit: ${{ github.sha }}